#!/bin/bash

dialog --title "问卷" --msgbox "欢迎来到我的简单问卷" 9 18
dialog --title "确认" --yesno "你将确认参加吗？" 9 18
if [ $? != 0 ]; then               #环境变量判断用户选择了yes还是no
	dialog --infobox "感谢您" 5 20
	sleep 2
	dialog --clear
	exit 0
fi
#将输入的名字重定向到_1.txt
dialog --title "问卷调查" --inputbox "请输入你的名字：" 9 30 2>_1.txt
Q_NAME=$(cat _1.txt)

dialog --menu "$Q_NAME, 你最喜欢什么类型的音乐" 15 30 4 1 "古典" 2 "爵士" 3 "乡村" 4 "其他" 2>_1.txt
Q_MUSIC=$(cat _1.txt)

if [ "$Q_MUSIC" = "1" ]; then
	dialog --title "喜欢古典" --msgbox "好的选择！" 12 25
else
	dialog --title "不喜欢古典" --msgbox "很遗憾！" 12 25
fi

sleep 2
dialog --clear

exit 0
