#!/bin/bash

yes_or_no(){

	echo "is your name $* ?"
	while true
	do
		echo -n "ENter yes or no: "
		read x
		case "$x" in 
			y | yes ) return 0;;
			n | no ) return 1;;
			* ) echo "Answer yes or no "
		esac
	done
}

echo "Original parameters are $*"

if yes_or_no "$1"							#$1作为函数的入参，函数返回0表示成功，返回1表示成功,没有返回值则一直循环。
then
	echo "Hi $1, nice name"
else
	echo "Never mind"
fi

exit 0

